# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dcd9d1de05c3ff9240b05b35072935b6302348ea25256cc29fca2296212ec485a126c955b9d0fc6ea338ed8f88e1276624de18af4dcc24a8a4ba33f9c786fde

test:
  secret_key_base: 511faaaecd9ef846d9c3cdcf3c9282fb99954cc982b870dbffec7095ad31c0e72601b950bc0f34b8c627c1163b7c4d3578f6db734207c5d7aa0e9bfc00d42cdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
